### ISSUE TITLE
Create User Page

### ISSUE THREAD

**Issue by cenah-mgt** [SyegiDaWae/cobagit#3]
# Description
Please create a page for creating user profile. 

## Requirement(s)
This user profile are related to repository owner.

### Todos
- [ ] create user_profile.html
- [ ] input html boiler plate
- [ ] show username and email
- [ ] show user description

## How to close this ticket

- create a file
- add file to git
- `git commit -m "FEAT: #3"`
- git push ...
